version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - zelda_network
    ports:
      - "${MONGO_EXT_PORT}:27017"
    volumes:
      - mongo_data:/data/db
      - ./backup:/backup
    command: >
      /bin/bash -c "
        mongod --bind_ip_all --fork --logpath /var/log/mongodb.log &&
        if [ ! -f /data/db/.restored ]; then
          echo '🗄️ Restaurant backup de zelda_botw...';
          mongorestore --db zelda_botw /backup/zelda_botw;
          touch /data/db/.restored;
        else
          echo '✅ Base de dades existent: no es restaura backup';
        fi &&
        tail -f /dev/null
      "
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_zelda
    networks:
      - zelda_network
    ports:
      - "${API_EXT_PORT}:${API_PORT}"
    depends_on:
      - mongodb
    environment:
      MONGO_SRV_URL: mongodb://mongodb:27017/zelda_botw
    restart: always

volumes:
  mongo_data:
networks:
  zelda_network: